# Generated by Django 5.1 on 2024-09-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/original/'),
        ),
    ]
