# Generated by Django 5.1 on 2024-09-27 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
