# Generated by Django 5.1 on 2024-09-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_alter_photo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
