# Generated by Django 5.1 on 2024-09-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_alter_photo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='price',
        ),
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(max_length=400, unique=True),
        ),
    ]
