# Generated by Django 5.1.3 on 2025-08-16 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_event_eventregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='active',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
    ]
