# Generated by Django 5.1 on 2024-09-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='user_type',
            field=models.CharField(max_length=20),
        ),
    ]
