# Generated by Django 5.1 on 2024-09-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuserprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'customer'), ('photographer', 'photographer')], max_length=30),
        ),
    ]
