# Generated by Django 5.1 on 2024-09-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuserprofile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bopcommission',
            name='user',
        ),
    ]
