# Generated by Django 5.1 on 2024-09-23 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_orders_user'),
        ('cms', '0010_alter_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='photo_owner',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='cms.photo'),
            preserve_default=False,
        ),
    ]
